variables:
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

stages:
  - test

cypress:
  stage: test
  # image: cypress/browsers:node14.15.0-chrome86-ff82
  cache:
    paths:
      - node_modules/
      - cache/Cypress/
  image: cypress/base:16.13.0
  script:
    - echo "Running pipeline..."
    #  install dependencies
    - npm install
    - npm install --save-dev cypress

    # - npx browserslist@latest --update-db
    # start the server in the background
    # - npm run start:ci &
    # run Cypress tests

    - npx cypress run
  tags:
    - docker

  # rules:
  #   - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_SCHEDULE == "0 14 * * 1,3"'










